#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — sets up an S3 bucket (AWS Free Tier) for Manzil client documents:
# a private bucket, CORS for direct browser uploads, a lifecycle rule to
# clean up abandoned multipart uploads, a least-privilege IAM policy, and a
# dedicated IAM user + access key for the backend app.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# This script lives in backend/scripts/ — write straight into backend/.env
# regardless of where the wizard is actually run from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

banner "Manzil — AWS S3 client-document storage setup"

# ── Stage 1: AWS CLI present? ───────────────────────────────────────────
stage "AWS CLI"
if command -v aws >/dev/null 2>&1; then
  say "Found: $(aws --version 2>&1)"
else
  warn "AWS CLI isn't installed — this wizard drives it directly, so it's required."
  printf '\n'
  say "Install it (Windows):"
  step "Download the MSI installer: https://awscli.amazonaws.com/AWSCLIV2.msi"
  step "Run it, accept defaults, then open a NEW terminal (PATH only updates for new shells)."
  step "Verify with: aws --version"
  printf '\n'
  say "Alternative (Git Bash / winget): winget install Amazon.AWSCLI"
  printf '\n'
  warn "Re-run this wizard after installing: bash scripts/aws-setup-wizard.sh"
  exit 1
fi

# ── Stage 2: Authenticate the CLI ───────────────────────────────────────
stage "Authenticate the AWS CLI"
if aws sts get-caller-identity >/dev/null 2>&1; then
  IDENTITY_ARN=$(aws sts get-caller-identity --query Arn --output text)
  say "Already authenticated as: $IDENTITY_ARN"
  confirm "Use this identity for setup?" || { warn "Run 'aws configure' with the identity you want, then re-run this wizard."; exit 1; }
else
  say "The CLI needs a bootstrap credential to create things with. Easiest: a personal"
  say "IAM user with the built-in 'AdministratorAccess' policy, used ONLY to run this"
  say "wizard — you can delete it afterwards; the app itself will use a separate,"
  say "narrowly-scoped user this wizard creates for it in a later stage."
  printf '\n'
  open_url "https://console.aws.amazon.com/iamv2/home#/users/create"
  step "User name: e.g. 'bootstrap-cli' → Next."
  step "Permissions options → Attach policies directly → search 'AdministratorAccess' → check it → Next → Create user."
  step "Open the new user → Security credentials tab → 'Create access key' → choose 'Command Line Interface (CLI)' → confirm → Create."
  step "Copy the Access key ID and Secret access key shown (the secret is shown ONCE)."
  printf '\n'
  say "Now run this in another terminal, pasting those two values when prompted:"
  note "    aws configure"
  note "    (set default region to whatever you plan to use, e.g. eu-west-2)"
  pause "Done running 'aws configure'? Press Enter to verify..."
  if ! aws sts get-caller-identity >/dev/null 2>&1; then
    warn "Still not authenticated — re-run 'aws configure' and this wizard again."
    exit 1
  fi
  say "Authenticated as: $(aws sts get-caller-identity --query Arn --output text)"
fi

# ── Stage 3: Create the bucket ──────────────────────────────────────────
stage "Create the S3 bucket"
say "Bucket names are globally unique across ALL of AWS, so we suggest a random suffix."
DEFAULT_SUFFIX=$(od -An -N4 -tx1 /dev/urandom 2>/dev/null | tr -d ' \n' || date +%s)
DEFAULT_BUCKET="manzil-client-docs-${DEFAULT_SUFFIX}"
ask AWS_REGION "AWS region (e.g. eu-west-2 for London):"
[[ -z "${AWS_REGION:-}" ]] && AWS_REGION="eu-west-2"
ask S3_BUCKET_NAME "Bucket name [suggested: $DEFAULT_BUCKET]:"
[[ -z "${S3_BUCKET_NAME:-}" ]] && S3_BUCKET_NAME="$DEFAULT_BUCKET"

if aws s3api head-bucket --bucket "$S3_BUCKET_NAME" >/dev/null 2>&1; then
  say "Bucket '$S3_BUCKET_NAME' already exists and is reachable with these credentials — reusing it."
else
  confirm "Create private bucket '$S3_BUCKET_NAME' in $AWS_REGION now?" || { warn "Aborted — nothing created."; exit 1; }
  if [[ "$AWS_REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$S3_BUCKET_NAME" --region "$AWS_REGION"
  else
    aws s3api create-bucket --bucket "$S3_BUCKET_NAME" --region "$AWS_REGION" \
      --create-bucket-configuration "LocationConstraint=$AWS_REGION"
  fi
  aws s3api put-public-access-block --bucket "$S3_BUCKET_NAME" --public-access-block-configuration \
    "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
  aws s3api put-bucket-encryption --bucket "$S3_BUCKET_NAME" --server-side-encryption-configuration \
    '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
  printf '  %s✓%s bucket created, public access blocked, default encryption on\n' "$GREEN" "$RESET"
fi
write_env AWS_REGION "$AWS_REGION"
write_env S3_BUCKET_NAME "$S3_BUCKET_NAME"

# ── Stage 4: CORS + lifecycle rule ──────────────────────────────────────
stage "CORS and cleanup rule"
say "The browser uploads straight to S3 with presigned URLs — the bucket must allow"
say "PUT/GET from the app's origin(s), and must expose the ETag header (the app's"
say "multipart upload needs to read each part's ETag from the S3 response)."
DEV_ORIGIN="http://localhost:5173"
ask PROD_ORIGIN "Production origin to also allow (blank to skip for now, e.g. https://app.manzilconsultancy.com):"

ORIGINS_JSON="\"$DEV_ORIGIN\""
[[ -n "${PROD_ORIGIN:-}" ]] && ORIGINS_JSON="$ORIGINS_JSON, \"$PROD_ORIGIN\""

cat > "$WORK_DIR/cors.json" <<EOF
{
  "CORSRules": [
    {
      "AllowedOrigins": [$ORIGINS_JSON],
      "AllowedMethods": ["PUT", "GET"],
      "AllowedHeaders": ["*"],
      "ExposeHeaders": ["ETag"],
      "MaxAgeSeconds": 3000
    }
  ]
}
EOF
aws s3api put-bucket-cors --bucket "$S3_BUCKET_NAME" --cors-configuration "file://$WORK_DIR/cors.json"
printf '  %s✓%s CORS applied for: %s\n' "$GREEN" "$RESET" "$DEV_ORIGIN${PROD_ORIGIN:+, $PROD_ORIGIN}"
note "Re-run this wizard any time to add another origin later — it's safe to repeat."

cat > "$WORK_DIR/lifecycle.json" <<'EOF'
{
  "Rules": [
    {
      "ID": "abort-incomplete-multipart-uploads",
      "Status": "Enabled",
      "Filter": {},
      "AbortIncompleteMultipartUpload": { "DaysAfterInitiation": 1 }
    }
  ]
}
EOF
aws s3api put-bucket-lifecycle-configuration --bucket "$S3_BUCKET_NAME" --lifecycle-configuration "file://$WORK_DIR/lifecycle.json"
printf '  %s✓%s abandoned multipart uploads now auto-clean after 1 day\n' "$GREEN" "$RESET"

# ── Stage 5: Least-privilege IAM policy + dedicated app user ────────────
stage "IAM policy and app user"
say "The backend app should never hold admin credentials. We'll scope a policy to"
say "exactly this bucket, and create a separate IAM user just for the app to use."

IAM_USER_NAME="manzil-app-s3"
IAM_POLICY_NAME="manzil-app-s3-policy"

cat > "$WORK_DIR/policy.json" <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ListBucketOnly",
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": "arn:aws:s3:::$S3_BUCKET_NAME"
    },
    {
      "Sid": "ObjectAndMultipartOps",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts"
      ],
      "Resource": "arn:aws:s3:::$S3_BUCKET_NAME/*"
    }
  ]
}
EOF

confirm "Create IAM user '$IAM_USER_NAME' + policy '$IAM_POLICY_NAME' scoped to just this bucket?" || { warn "Aborted before creating IAM resources."; exit 1; }

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
POLICY_ARN="arn:aws:iam::${ACCOUNT_ID}:policy/${IAM_POLICY_NAME}"

if aws iam get-policy --policy-arn "$POLICY_ARN" >/dev/null 2>&1; then
  say "Policy '$IAM_POLICY_NAME' already exists — reusing it (not modifying its rules; edit in console if the bucket name changed)."
else
  aws iam create-policy --policy-name "$IAM_POLICY_NAME" --policy-document "file://$WORK_DIR/policy.json" >/dev/null
  printf '  %s✓%s policy created: %s\n' "$GREEN" "$RESET" "$POLICY_ARN"
fi

if aws iam get-user --user-name "$IAM_USER_NAME" >/dev/null 2>&1; then
  say "IAM user '$IAM_USER_NAME' already exists — reusing it."
else
  aws iam create-user --user-name "$IAM_USER_NAME" >/dev/null
  printf '  %s✓%s user created: %s\n' "$GREEN" "$RESET" "$IAM_USER_NAME"
fi
aws iam attach-user-policy --user-name "$IAM_USER_NAME" --policy-arn "$POLICY_ARN"

EXISTING_KEYS=$(aws iam list-access-keys --user-name "$IAM_USER_NAME" --query 'AccessKeyMetadata[].AccessKeyId' --output text)
if [[ -n "$EXISTING_KEYS" ]]; then
  warn "'$IAM_USER_NAME' already has an access key ($EXISTING_KEYS)."
  if confirm "Create a NEW key anyway (old one keeps working — remember to delete it later if unused)?"; then
    CREATE_KEY=1
  else
    CREATE_KEY=0
    warn "Skipping key creation — you'll need to reuse/retrieve the existing secret yourself (AWS won't show it again)."
  fi
else
  CREATE_KEY=1
fi

if [[ "$CREATE_KEY" == "1" ]]; then
  KEY_JSON=$(aws iam create-access-key --user-name "$IAM_USER_NAME")
  AWS_ACCESS_KEY_ID=$(printf '%s' "$KEY_JSON" | grep -o '"AccessKeyId": *"[^"]*"' | cut -d'"' -f4)
  AWS_SECRET_ACCESS_KEY=$(printf '%s' "$KEY_JSON" | grep -o '"SecretAccessKey": *"[^"]*"' | cut -d'"' -f4)
  write_env AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
  write_env AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
  printf '  %s✓%s access key created and saved to %s\n' "$GREEN" "$RESET" "$ENV_FILE"
fi

# ── Stage 6: Free Tier awareness ────────────────────────────────────────
stage "Free Tier limits"
say "This bucket runs on the AWS Free Tier for your account's first 12 months:"
step "5 GB of S3 Standard storage"
step "20,000 GET requests / month"
step "2,000 PUT, COPY, POST or LIST requests / month"
printf '\n'
say "At ~7-10 documents per client averaging a couple MB each, that's roughly"
say "500+ clients' worth of storage before you'd approach the 5GB line — PUT"
say "requests (one per file, or per part for large multipart files) are the more"
say "likely thing to watch if upload volume gets heavy. Set a Billing budget alert"
say "if you want a safety net:"
open_url "https://console.aws.amazon.com/billing/home#/budgets"
pause "Press Enter once you've had a look (or skip)..."

finish
note "backend/.env already has placeholders for AWS_REGION / AWS_ACCESS_KEY_ID /"
note "AWS_SECRET_ACCESS_KEY / S3_BUCKET_NAME — this wizard just filled them in."
note "Restart the backend dev server (nodemon) to pick up the new .env values."
